#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width         4
bspc config window_gap          7
bspc config focus_follows_pointer true
# bspc config focused_border_color "#5E81AC"
bspc config focused_border_color "#2D4F67"
bspc config normal_border_color "#000000"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
